"""add_sale_statuses_and_quality_fields

Revision ID: 1f14700cd1e1
Revises: 68d36f5db187
Create Date: 2026-08-04 19:52:52.297264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f14700cd1e1'
down_revision: Union[str, Sequence[str], None] = '68d36f5db187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('received_quality_pct', sa.DECIMAL(precision=5, scale=2), nullable=True), schema='inventory')
    op.add_column('sale_items', sa.Column('status', sa.String(length=50), nullable=True), schema='sales')
    op.add_column('sale_items', sa.Column('substitutions', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('assembly_started_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('assembly_completed_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('cancellation_reason', sa.Text(), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales', sa.Column('return_reason', sa.Text(), nullable=True), schema='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'return_reason', schema='sales')
    op.drop_column('sales', 'returned_at', schema='sales')
    op.drop_column('sales', 'cancellation_reason', schema='sales')
    op.drop_column('sales', 'cancelled_at', schema='sales')
    op.drop_column('sales', 'completed_at', schema='sales')
    op.drop_column('sales', 'shipped_at', schema='sales')
    op.drop_column('sales', 'assembly_completed_at', schema='sales')
    op.drop_column('sales', 'assembly_started_at', schema='sales')
    op.drop_column('sale_items', 'substitutions', schema='sales')
    op.drop_column('sale_items', 'status', schema='sales')
    op.drop_column('batches', 'received_quality_pct', schema='inventory')
    # ### end Alembic commands ###
