"""remove_packaging_tables

Revision ID: 40c662579fcf
Revises: 582c69abf956
Create Date: 2026-09-30 16:37:05.342236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40c662579fcf'
down_revision: Union[str, Sequence[str], None] = '582c69abf956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удаляем таблицы с CASCADE (есть FK зависимости между ними)
    op.execute('DROP TABLE IF EXISTS inventory.packaging_adjustments CASCADE')
    op.execute('DROP TABLE IF EXISTS inventory.packaging_consumption CASCADE')
    op.execute('DROP TABLE IF EXISTS inventory.packaging_openings CASCADE')
    op.execute('DROP TABLE IF EXISTS inventory.packaging_units CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_adjustments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('opening_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('normative_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('actual_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('adjustment_factor', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=False),
    sa.Column('is_anomaly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('anomaly_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cost_impact', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opening_id'], ['inventory.packaging_openings.id'], name=op.f('packaging_adjustments_opening_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('packaging_adjustments_pkey')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_adjustments_id'), 'packaging_adjustments', ['id'], unique=False, schema='inventory')
    op.create_table('packaging_consumption',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('opening_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('normative_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('normative_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opening_id'], ['inventory.packaging_openings.id'], name=op.f('packaging_consumption_opening_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('packaging_consumption_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('packaging_consumption_pkey')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_consumption_id'), 'packaging_consumption', ['id'], unique=False, schema='inventory')
    op.create_table('packaging_openings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('packaging_unit_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('opened_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('initial_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('final_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opened_by'], ['users.users.id'], name=op.f('packaging_openings_opened_by_fkey')),
    sa.ForeignKeyConstraint(['packaging_unit_id'], ['inventory.packaging_units.id'], name=op.f('packaging_openings_packaging_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('packaging_openings_pkey')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_openings_id'), 'packaging_openings', ['id'], unique=False, schema='inventory')
    op.create_table('packaging_units',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('base_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('base_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actual_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('packaging_units_product_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['catalog.suppliers.id'], name=op.f('packaging_units_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('packaging_units_pkey')),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_units_id'), 'packaging_units', ['id'], unique=False, schema='inventory')
    # ### end Alembic commands ###
