"""add is_system column to roles

Revision ID: 4c10c2fcb9ba
Revises: 1f14700cd1e1
Create Date: 2026-08-05 16:45:33.558599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c10c2fcb9ba'
down_revision: Union[str, Sequence[str], None] = '1f14700cd1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), nullable=True), schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_system', schema='users')
    # ### end Alembic commands ###
