"""add product_type to purchase_order_items

Revision ID: 582c69abf956
Revises: cbff6307b406
Create Date: 2026-09-27 16:46:20.188882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582c69abf956'
down_revision: Union[str, Sequence[str], None] = 'cbff6307b406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('product_type', sa.String(length=20), nullable=True), schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'product_type', schema='inventory')
    # ### end Alembic commands ###
