"""complete tz compliant schema

Revision ID: 68d36f5db187
Revises: 
Create Date: 2026-07-19 18:46:59.992803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d36f5db187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_categories_id'), 'categories', ['id'], unique=False, schema='catalog')
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tolerance_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_recipes_id'), 'recipes', ['id'], unique=False, schema='catalog')
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_suppliers_id'), 'suppliers', ['id'], unique=False, schema='catalog')
    op.create_table('marketplaces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('default_logistics_included', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='integrations'
    )
    op.create_index(op.f('ix_integrations_marketplaces_id'), 'marketplaces', ['id'], unique=False, schema='integrations')
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('store_type', sa.String(length=50), nullable=False),
    sa.Column('marketplace_id', sa.BigInteger(), nullable=True),
    sa.Column('external_store_id', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='stores'
    )
    op.create_index(op.f('ix_stores_stores_id'), 'stores', ['id'], unique=False, schema='stores')
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_permissions_id'), 'permissions', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_permissions_name'), 'permissions', ['name'], unique=True, schema='users')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_roles_id'), 'roles', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_roles_name'), 'roles', ['name'], unique=True, schema='users')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_id'), 'users', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=True, schema='users')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.categories.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['catalog.recipes.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['catalog.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_products_id'), 'products', ['id'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_products_sku'), 'products', ['sku'], unique=True, schema='catalog')
    op.create_table('profit_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('period_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('target_revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('target_profit', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('target_margin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('actual_revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('actual_profit', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('forecast_profit', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('forecast_gap', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('marketplace_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_profit_targets_id'), 'profit_targets', ['id'], unique=False, schema='finance')
    op.create_table('marketplace_fees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('marketplace_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('fee_name', sa.String(length=200), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=False),
    sa.Column('fixed_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applies_to', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['integrations.marketplaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='integrations'
    )
    op.create_index(op.f('ix_integrations_marketplace_fees_id'), 'marketplace_fees', ['id'], unique=False, schema='integrations')
    op.create_table('sync_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('system_id', sa.BigInteger(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['integrations.marketplaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='integrations'
    )
    op.create_index(op.f('ix_integrations_sync_logs_id'), 'sync_logs', ['id'], unique=False, schema='integrations')
    op.create_table('sales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sale_number', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('marketplace_id', sa.BigInteger(), nullable=True),
    sa.Column('external_order_id', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_fees', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_number'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sales_id'), 'sales', ['id'], unique=False, schema='sales')
    op.create_table('store_priorities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_margin_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_daily_sales', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='stores'
    )
    op.create_index(op.f('ix_stores_store_priorities_id'), 'store_priorities', ['id'], unique=False, schema='stores')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['users.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['users.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='users'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='users'
    )
    op.create_table('component_demand_forecast',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('avg_demand', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('std_deviation', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_90_pct', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_95_pct', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_99_pct', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('demand_by_recipe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_component_demand_forecast_id'), 'component_demand_forecast', ['id'], unique=False, schema='analytics')
    op.create_table('product_sales_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('avg_daily_sales', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('std_deviation', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('sales_by_weekday', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sales_by_hour', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coefficient_of_variation', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_product_sales_stats_id'), 'product_sales_stats', ['id'], unique=False, schema='analytics')
    op.create_table('purchase_recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('days_to_cover', sa.Integer(), nullable=False),
    sa.Column('forecasted_demand', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('current_stock', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('expected_waste', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('recommended_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('confidence_level', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['catalog.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_purchase_recommendations_id'), 'purchase_recommendations', ['id'], unique=False, schema='analytics')
    op.create_table('recipe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['catalog.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_recipe_items_id'), 'recipe_items', ['id'], unique=False, schema='catalog')
    op.create_table('pricing_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('marketplace_id', sa.BigInteger(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('markup_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('target_margin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('priority', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_pricing_rules_id'), 'pricing_rules', ['id'], unique=False, schema='finance')
    op.create_table('marketplace_category_fees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('marketplace_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_id', sa.BigInteger(), nullable=False),
    sa.Column('override_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('override_fixed', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.categories.id'], ),
    sa.ForeignKeyConstraint(['fee_id'], ['integrations.marketplace_fees.id'], ),
    sa.ForeignKeyConstraint(['marketplace_id'], ['integrations.marketplaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='integrations'
    )
    op.create_index(op.f('ix_integrations_marketplace_category_fees_id'), 'marketplace_category_fees', ['id'], unique=False, schema='integrations')
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('current_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['catalog.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_batches_id'), 'batches', ['id'], unique=False, schema='inventory')
    op.create_table('packaging_units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('base_quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('base_unit', sa.String(length=50), nullable=False),
    sa.Column('actual_quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['catalog.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_units_id'), 'packaging_units', ['id'], unique=False, schema='inventory')
    op.create_table('stock',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_id'), 'stock', ['id'], unique=False, schema='inventory')
    op.create_table('sale_fees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sale_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_id', sa.BigInteger(), nullable=True),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('fee_name', sa.String(length=200), nullable=False),
    sa.Column('base_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('calculated_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sale_fees_id'), 'sale_fees', ['id'], unique=False, schema='sales')
    op.create_table('store_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('store_name', sa.String(length=300), nullable=False),
    sa.Column('store_sku', sa.String(length=100), nullable=True),
    sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('is_listed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_store_product'),
    schema='stores'
    )
    op.create_index(op.f('ix_stores_store_products_id'), 'store_products', ['id'], unique=False, schema='stores')
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('old_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('new_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_price_history_id'), 'price_history', ['id'], unique=False, schema='finance')
    op.create_table('movements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('sale_id', sa.BigInteger(), nullable=True),
    sa.Column('write_off_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'movements', ['id'], unique=False, schema='inventory')
    op.create_table('packaging_openings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('packaging_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opened_by', sa.BigInteger(), nullable=True),
    sa.Column('initial_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_qty', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opened_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['packaging_unit_id'], ['inventory.packaging_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_openings_id'), 'packaging_openings', ['id'], unique=False, schema='inventory')
    op.create_table('write_offs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('days_in_stock', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_write_offs_id'), 'write_offs', ['id'], unique=False, schema='inventory')
    op.create_table('sale_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sale_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('actual_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['catalog.recipes.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_sale_items_id'), 'sale_items', ['id'], unique=False, schema='sales')
    op.create_table('availability_alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('required_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('available_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('shortage_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory.batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='stores'
    )
    op.create_index(op.f('ix_stores_availability_alerts_id'), 'availability_alerts', ['id'], unique=False, schema='stores')
    op.create_table('packaging_adjustments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('opening_id', sa.BigInteger(), nullable=False),
    sa.Column('normative_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('actual_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('adjustment_factor', sa.DECIMAL(precision=5, scale=3), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reason', sa.String(length=200), nullable=True),
    sa.Column('cost_impact', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opening_id'], ['inventory.packaging_openings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_adjustments_id'), 'packaging_adjustments', ['id'], unique=False, schema='inventory')
    op.create_table('packaging_consumption',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('opening_id', sa.BigInteger(), nullable=False),
    sa.Column('sale_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('normative_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('normative_unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opening_id'], ['inventory.packaging_openings.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_packaging_consumption_id'), 'packaging_consumption', ['id'], unique=False, schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_packaging_consumption_id'), table_name='packaging_consumption', schema='inventory')
    op.drop_table('packaging_consumption', schema='inventory')
    op.drop_index(op.f('ix_inventory_packaging_adjustments_id'), table_name='packaging_adjustments', schema='inventory')
    op.drop_table('packaging_adjustments', schema='inventory')
    op.drop_index(op.f('ix_stores_availability_alerts_id'), table_name='availability_alerts', schema='stores')
    op.drop_table('availability_alerts', schema='stores')
    op.drop_index(op.f('ix_sales_sale_items_id'), table_name='sale_items', schema='sales')
    op.drop_table('sale_items', schema='sales')
    op.drop_index(op.f('ix_inventory_write_offs_id'), table_name='write_offs', schema='inventory')
    op.drop_table('write_offs', schema='inventory')
    op.drop_index(op.f('ix_inventory_packaging_openings_id'), table_name='packaging_openings', schema='inventory')
    op.drop_table('packaging_openings', schema='inventory')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='movements', schema='inventory')
    op.drop_table('movements', schema='inventory')
    op.drop_index(op.f('ix_finance_price_history_id'), table_name='price_history', schema='finance')
    op.drop_table('price_history', schema='finance')
    op.drop_index(op.f('ix_stores_store_products_id'), table_name='store_products', schema='stores')
    op.drop_table('store_products', schema='stores')
    op.drop_index(op.f('ix_sales_sale_fees_id'), table_name='sale_fees', schema='sales')
    op.drop_table('sale_fees', schema='sales')
    op.drop_index(op.f('ix_inventory_stock_id'), table_name='stock', schema='inventory')
    op.drop_table('stock', schema='inventory')
    op.drop_index(op.f('ix_inventory_packaging_units_id'), table_name='packaging_units', schema='inventory')
    op.drop_table('packaging_units', schema='inventory')
    op.drop_index(op.f('ix_inventory_batches_id'), table_name='batches', schema='inventory')
    op.drop_table('batches', schema='inventory')
    op.drop_index(op.f('ix_integrations_marketplace_category_fees_id'), table_name='marketplace_category_fees', schema='integrations')
    op.drop_table('marketplace_category_fees', schema='integrations')
    op.drop_index(op.f('ix_finance_pricing_rules_id'), table_name='pricing_rules', schema='finance')
    op.drop_table('pricing_rules', schema='finance')
    op.drop_index(op.f('ix_catalog_recipe_items_id'), table_name='recipe_items', schema='catalog')
    op.drop_table('recipe_items', schema='catalog')
    op.drop_index(op.f('ix_analytics_purchase_recommendations_id'), table_name='purchase_recommendations', schema='analytics')
    op.drop_table('purchase_recommendations', schema='analytics')
    op.drop_index(op.f('ix_analytics_product_sales_stats_id'), table_name='product_sales_stats', schema='analytics')
    op.drop_table('product_sales_stats', schema='analytics')
    op.drop_index(op.f('ix_analytics_component_demand_forecast_id'), table_name='component_demand_forecast', schema='analytics')
    op.drop_table('component_demand_forecast', schema='analytics')
    op.drop_table('user_roles', schema='users')
    op.drop_table('role_permissions', schema='users')
    op.drop_index(op.f('ix_stores_store_priorities_id'), table_name='store_priorities', schema='stores')
    op.drop_table('store_priorities', schema='stores')
    op.drop_index(op.f('ix_sales_sales_id'), table_name='sales', schema='sales')
    op.drop_table('sales', schema='sales')
    op.drop_index(op.f('ix_integrations_sync_logs_id'), table_name='sync_logs', schema='integrations')
    op.drop_table('sync_logs', schema='integrations')
    op.drop_index(op.f('ix_integrations_marketplace_fees_id'), table_name='marketplace_fees', schema='integrations')
    op.drop_table('marketplace_fees', schema='integrations')
    op.drop_index(op.f('ix_finance_profit_targets_id'), table_name='profit_targets', schema='finance')
    op.drop_table('profit_targets', schema='finance')
    op.drop_index(op.f('ix_catalog_products_sku'), table_name='products', schema='catalog')
    op.drop_index(op.f('ix_catalog_products_id'), table_name='products', schema='catalog')
    op.drop_table('products', schema='catalog')
    op.drop_index(op.f('ix_users_users_username'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_id'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    op.drop_index(op.f('ix_users_roles_name'), table_name='roles', schema='users')
    op.drop_index(op.f('ix_users_roles_id'), table_name='roles', schema='users')
    op.drop_table('roles', schema='users')
    op.drop_index(op.f('ix_users_permissions_name'), table_name='permissions', schema='users')
    op.drop_index(op.f('ix_users_permissions_id'), table_name='permissions', schema='users')
    op.drop_table('permissions', schema='users')
    op.drop_index(op.f('ix_stores_stores_id'), table_name='stores', schema='stores')
    op.drop_table('stores', schema='stores')
    op.drop_index(op.f('ix_integrations_marketplaces_id'), table_name='marketplaces', schema='integrations')
    op.drop_table('marketplaces', schema='integrations')
    op.drop_index(op.f('ix_catalog_suppliers_id'), table_name='suppliers', schema='catalog')
    op.drop_table('suppliers', schema='catalog')
    op.drop_index(op.f('ix_catalog_recipes_id'), table_name='recipes', schema='catalog')
    op.drop_table('recipes', schema='catalog')
    op.drop_index(op.f('ix_catalog_categories_id'), table_name='categories', schema='catalog')
    op.drop_table('categories', schema='catalog')
    # ### end Alembic commands ###
