"""add_purchase_orders_tables

Revision ID: a2609cef9d94
Revises: e3ea32964555
Create Date: 2026-09-25 17:28:22.960586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2609cef9d94'
down_revision: Union[str, Sequence[str], None] = 'e3ea32964555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['catalog.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_purchase_orders_id'), 'purchase_orders', ['id'], unique=False, schema='inventory')
    op.create_table('purchase_order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('ordered_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('received_qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['inventory.purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False, schema='inventory')
    op.create_table('purchase_order_receipts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.BigInteger(), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['inventory.purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_purchase_order_receipts_id'), 'purchase_order_receipts', ['id'], unique=False, schema='inventory')
    op.create_table('purchase_order_receipt_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['inventory.purchase_order_receipts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_purchase_order_receipt_items_id'), 'purchase_order_receipt_items', ['id'], unique=False, schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_purchase_order_receipt_items_id'), table_name='purchase_order_receipt_items', schema='inventory')
    op.drop_table('purchase_order_receipt_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_purchase_order_receipts_id'), table_name='purchase_order_receipts', schema='inventory')
    op.drop_table('purchase_order_receipts', schema='inventory')
    op.drop_index(op.f('ix_inventory_purchase_order_items_id'), table_name='purchase_order_items', schema='inventory')
    op.drop_table('purchase_order_items', schema='inventory')
    op.drop_index(op.f('ix_inventory_purchase_orders_id'), table_name='purchase_orders', schema='inventory')
    op.drop_table('purchase_orders', schema='inventory')
    # ### end Alembic commands ###
