"""purchase_order_invoice_waybill_fields

Revision ID: cbff6307b406
Revises: a2609cef9d94
Create Date: 2026-09-26 20:33:32.659652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbff6307b406'
down_revision: Union[str, Sequence[str], None] = 'a2609cef9d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('invoice_date', sa.Date(), nullable=True), schema='inventory')
    op.add_column('purchase_orders', sa.Column('supplier_waybill_number', sa.String(length=100), nullable=True), schema='inventory')
    op.alter_column('purchase_orders', 'supplier_invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'supplier_invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='inventory')
    op.drop_column('purchase_orders', 'supplier_waybill_number', schema='inventory')
    op.drop_column('purchase_orders', 'invoice_date', schema='inventory')
    # ### end Alembic commands ###
