"""add paid_amount to purchase_orders

Revision ID: fddeee32640d
Revises: a1b2c3d4e5f6
Create Date: 2026-10-02 12:34:47.521979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddeee32640d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('paid_amount', sa.DECIMAL(precision=12, scale=2), nullable=False, server_default='0'), schema='inventory')
    op.create_foreign_key(None, 'write_offs', 'products', ['product_id'], ['id'], source_schema='inventory', referent_schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'write_offs', schema='inventory', type_='foreignkey')
    op.drop_column('purchase_orders', 'paid_amount', schema='inventory')
    # ### end Alembic commands ###
